# Generated by Django 5.2 on 2025-05-06 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marsruts',
            fields=[
                ('marsruts_id', models.AutoField(primary_key=True, serialize=False)),
                ('numurs', models.CharField(max_length=20, verbose_name='Number')),
                ('nosaukums', models.CharField(max_length=255, verbose_name='Name')),
                ('apraksts', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Pietura',
            fields=[
                ('pietura_id', models.AutoField(primary_key=True, serialize=False)),
                ('nosaukums', models.CharField(max_length=255, verbose_name='Name')),
                ('adrese', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('gps_koordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Coordinates')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
            },
        ),
        migrations.CreateModel(
            name='Pilseta',
            fields=[
                ('pilseta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nosaukums', models.CharField(max_length=100, verbose_name='Name')),
                ('valsts', models.CharField(max_length=100, verbose_name='Country')),
                ('iedzivotaju_skaits', models.IntegerField(blank=True, null=True, verbose_name='Population')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='TransportaVeids',
            fields=[
                ('veids_id', models.AutoField(primary_key=True, serialize=False)),
                ('nosaukums', models.CharField(max_length=50, verbose_name='Name')),
                ('vides_ietekme', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Environmental Impact')),
                ('apraksts', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Transport Type',
                'verbose_name_plural': 'Transport Types',
            },
        ),
        migrations.CreateModel(
            name='MarsrutaPietura',
            fields=[
                ('mars_piet_id', models.AutoField(primary_key=True, serialize=False)),
                ('kartas_nr', models.IntegerField(verbose_name='Order')),
                ('laiks_lidz_nakamai', models.IntegerField(blank=True, help_text='Time in minutes', null=True, verbose_name='Time to Next Stop')),
                ('marsruts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.marsruts', verbose_name='Route')),
                ('pietura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.pietura', verbose_name='Stop')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['marsruts', 'kartas_nr'],
            },
        ),
        migrations.AddField(
            model_name='pietura',
            name='pilseta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.pilseta', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='marsruts',
            name='pilseta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.pilseta', verbose_name='City'),
        ),
        migrations.CreateModel(
            name='SatiksmeStavoklis',
            fields=[
                ('stavoklis_id', models.AutoField(primary_key=True, serialize=False)),
                ('tips', models.CharField(choices=[('sastregums', 'Congestion'), ('cela_darbi', 'Road Works'), ('negadijums', 'Accident'), ('atruma_ierobezojums', 'Speed Limit'), ('cits', 'Other')], max_length=50, verbose_name='Type')),
                ('apraksts', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cela_posms', models.CharField(max_length=255, verbose_name='Road Section')),
                ('intensitate_min', models.IntegerField(blank=True, help_text='Duration of delay in minutes', null=True, verbose_name='Intensity (min)')),
                ('gps_koordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Coordinates')),
                ('sakuma_laiks', models.DateTimeField(verbose_name='Start Time')),
                ('beigu_laiks', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('pilseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.pilseta', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Traffic Condition',
                'verbose_name_plural': 'Traffic Conditions',
            },
        ),
        migrations.CreateModel(
            name='Transportlidzeklis',
            fields=[
                ('transp_id', models.AutoField(primary_key=True, serialize=False)),
                ('numurs', models.CharField(max_length=20, verbose_name='Number')),
                ('noslogojums', models.IntegerField(blank=True, help_text='Congestion level from 0 to 5', null=True, verbose_name='Congestion')),
                ('statuss', models.CharField(blank=True, choices=[('aktīvs', 'Active'), ('remontā', 'In Repair'), ('rezervē', 'In Reserve'), ('neaktīvs', 'Inactive')], max_length=20, null=True, verbose_name='Status')),
                ('marsruts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.marsruts', verbose_name='Route')),
                ('veids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportaveids', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='LietotajaZinojums',
            fields=[
                ('zinojums_id', models.AutoField(primary_key=True, serialize=False)),
                ('tips', models.CharField(choices=[('sastregums', 'Congestion'), ('transporta_noslogojums', 'Vehicle Congestion'), ('cela_stavoklis', 'Road Condition'), ('pietura_stavoklis', 'Stop Condition'), ('negadijums', 'Accident'), ('cits', 'Other')], max_length=100, verbose_name='Type')),
                ('apraksts', models.TextField(verbose_name='Description')),
                ('gps_koordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Coordinates')),
                ('laiks', models.DateTimeField(verbose_name='Time')),
                ('pasazieru_skaits', models.IntegerField(blank=True, null=True, verbose_name='Passenger Count')),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('marsruts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.marsruts', verbose_name='Route')),
                ('pietura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.pietura', verbose_name='Stop')),
                ('transp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportlidzeklis', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
            },
        ),
        migrations.CreateModel(
            name='KustibasGrafiks',
            fields=[
                ('grafiks_id', models.AutoField(primary_key=True, serialize=False)),
                ('atiesanas_laiks', models.TimeField(verbose_name='Departure Time')),
                ('ierasanas_laiks', models.TimeField(verbose_name='Arrival Time')),
                ('nedelas_diena', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Weekday')),
                ('marsruts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.marsruts', verbose_name='Route')),
                ('transp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportlidzeklis', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
