# Generated by Django 5.2 on 2025-06-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marsruts',
            options={},
        ),
        migrations.AlterModelTable(
            name='marsruts',
            table='transport_marsruts',
        ),
        migrations.CreateModel(
            name='Atsauksme',
            fields=[
                ('atsauksme_id', models.AutoField(primary_key=True, serialize=False)),
                ('teksts', models.TextField(verbose_name='Review Text')),
                ('laiks', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('novērtējums', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rating')),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('marsruts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.marsruts', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'unique_together': {('lietotajs', 'marsruts')},
            },
        ),
    ]
