# Generated by Django 5.2 on 2025-06-02 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_marsruts_options_alter_marsruts_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='transport.marsruts', verbose_name='Route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_routes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite Route',
                'verbose_name_plural': 'Favorite Routes',
                'unique_together': {('user', 'route')},
            },
        ),
    ]
